<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
	</array>
	<key>name</key>
	<string>CFG Game Configuration</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>\b\d+\.?(?:\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>double quoted string</string>
			<key>match</key>
			<string>\"[^\"]+\"</string>
			<key>name</key>
			<string>string.quoted.double.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>various keywords</string>
			<key>match</key>
			<string>\b(?:wait|echo|exec)\b</string>
			<key>name</key>
			<string>entity.other.attribute-name.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>alias</string>
			<key>match</key>
			<string>\balias\b</string>
			<key>name</key>
			<string>entity.name.function.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>binds</string>
			<key>match</key>
			<string>\b(?:(?:(?:un)?bind(?:all)?))\b</string>
			<key>name</key>
			<string>keyword.cfg</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment</string>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.cfg</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cfg</string>
	<key>uuid</key>
	<string>6f9ed479-bf11-476a-8f6a-8b013f808b01</string>
</dict>
</plist>
